### ISSUE TITLE
Json module in installing

### ISSUE THREAD

**Issue by Chen-bio** [broadinstitute/viral-ngs#193]
I tried to install the script one step by step, however, i always meet the following problem. It seems by decodes. Anyone can help me?

[admin@bio-server viral-ngs]$ python3.4 taxon_filter.py trim_trimmomatic fastq1 fastq2 pfastq1 pfastq2 clipfasta
2016-01-14 22:39:26,255 - cmd:130:main_argparse - INFO - software version: v1.2.0-2-ge1312c6-dirty, python version: 3.4.4 (default, Jan 14 2016, 22:20:19) 
[GCC 5.2.0]
2016-01-14 22:39:26,255 - cmd:132:main_argparse - INFO - command: taxon_filter.py trim_trimmomatic inFastq1=fastq1 tmp_dirKeep=False pairedOutFastq1=pfastq1 tmp_dir=/tmp inFastq2=fastq2 pairedOutFastq2=pfastq2 clipFasta=clipfasta loglevel=DEBUG
2016-01-14 22:39:26,256 - cmd:144:main_argparse - DEBUG - using tempDir: /tmp/tmp-taxon_filter-trim_trimmomatic-aekd6t7s
Traceback (most recent call last):
  File "taxon_filter.py", line 792, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "/home/admin/viral-ngs/util/cmd.py", line 147, in main_argparse
    ret = args.func_main(args)
  File "/home/admin/viral-ngs/util/cmd.py", line 77, in _main
    mainfunc(**args2)
  File "taxon_filter.py", line 96, in trimmomatic
    trimmomaticPath = tools.trimmomatic.TrimmomaticTool().install_and_get_path()
  File "/home/admin/viral-ngs/tools/__init__.py", line 104, in install_and_get_path
    self.install()
  File "/home/admin/viral-ngs/tools/__init__.py", line 81, in install
    m.attempt_install()
  File "/home/admin/viral-ngs/tools/__init__.py", line 125, in attempt_install
    self._attempt_install()
  File "/home/admin/viral-ngs/tools/__init__.py", line 268, in _attempt_install
    data = json.loads(result.stdout.decode("UTF-8"))
  File "/usr/local/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by tomkinsc** [comment]
Hi, @Chen-bio. I'm sorry you've hit a snag in running viral-ngs. It looks like the tool install process is failing. In an effort to improve portability, our most recent release of viral-ngs shifted the install of component tools from custom installs to ones based on conda packages, and the docs do not yet reflect the reliance on conda. You might try re-running the command after installing [miniconda](http://conda.pydata.org/docs/install/quick.html#miniconda-quick-install-requirements) (or Anaconda). I will be submitting a fix to better fall back to the old install methods, as well as an update the docs.

**Comment by tomkinsc** [comment]
I took a closer look at the code and confirmed that you should have received a "conda must be installed" error if conda is not installed. Do you have conda installed already? I'm wondering if this may be a character encoding problem related to our parsing of the conda json output as UTF-8. What platform are you running on? What is the output if you run these commands?

```bash
locale charmap
echo $LANG
echo $LC_CTYPE
echo $LC_ALL
```

**Comment by tomkinsc** [comment]
There's a new release you might try.

With release [v1.2.1](https://github.com/broadinstitute/viral-ngs/releases/tag/v1.2.1), viral-ngs falls back to our custom install methods when we fail to decode the conda json response. It also adds logging for such cases.

**Comment by Chen-bio** [comment]
Yes. "I have received the condo must be installed". and I installed the conda.  json package seems have the problem in transfer the coding. My commond should be UTF-8, but it might be zh_CN. UTF-8. I'd try your new release, at first.

**Comment by Chen-bio** [comment]
It works. Thank you very much.

**Comment by Chen-bio** [comment]
The new release is OK.
