### ISSUE TITLE
errors in intrahost.py

### ISSUE THREAD

**Issue by Chen-bio** [broadinstitute/viral-ngs#196]
@tomkinsc the pipeline stopped with the following information:
subprocess.CalledProcessError: Command '['/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/tools/binaries/V-Phaser-2.0/linux64/variant_caller', '-i', 'test.bam', '-o', '/tmp/tmpSpOFTivphaser2']' returned non-zero exit status -8
I checked the files all exist, but it return an error information.
Thanks for your help.

Other raw information:
Traceback (most recent call last):
  File "../viral-ngs-1.2.1/intrahost.py", line 1126, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/util/cmd.py", line 159, in main_argparse
    ret = args.func_main(args)
  File "/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/util/cmd.py", line 77, in _main
    mainfunc(**args2)
  File "../viral-ngs-1.2.1/intrahost.py", line 126, in vphaser_one_sample
    for row in libraryFilteredIter:
  File "../viral-ngs-1.2.1/intrahost.py", line 202, in compute_library_bias
    for row in isnvs:
  File "../viral-ngs-1.2.1/intrahost.py", line 139, in filter_strand_bias
    for row in isnvs:
  File "/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/tools/vphaser2.py", line 61, in iterate
    self.execute(inBam, outdir, numThreads)
  File "/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/tools/vphaser2.py", line 45, in execute
    subprocess.check_output(cmd, env=envCopy, stderr=subprocess.STDOUT)
  File "/software/biosoft/software/qiime/python2.7.8/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/datapool/bioinfo/chenchen/01132016ebola/viral-ngs-1.2.1/tools/binaries/V-Phaser-2.0/linux64/variant_caller', '-i', 'test.bam', '-o', '/tmp/tmpSpOFTivphaser2']' returned non-zero exit status -8

**Comment by tomkinsc** [comment]
What operating system are you running this under?

**Comment by Chen-bio** [comment]
I am running with centos. The bam file without sorting as an input file, will cause the above conditions.. Many thanks,

**Comment by tomkinsc** [comment]
Indeed, a sorted bam file is [noted](https://www.broadinstitute.org/software/viral/docs/VPhaserII.pdf) as a prerequisite for running V-Phaser. If calling `vphaser_one_sample` directly, the input currently needs to be sorted. For quick reference, this can be done with samtools on the command line: 

[`samtools sort -T /tmp/aln.sorted -o aln.sorted.bam aln.bam`](http://www.htslib.org/doc/samtools.html)

 We could perhaps automatically sort any bam files bearing an "unsorted" sort order (SO) flag. 

@Chen-bio, I see you marked this issue closed. Do you consider it resolved?

**Comment by tomkinsc** [comment]
Just a note that as of [v1.2.2](https://github.com/broadinstitute/viral-ngs/releases/tag/v1.2.2), bam files are sorted prior to running vphaser if they are passed in with SO=="unsorted".

**Comment by Chen-bio** [comment]
Thanks, @tomkinsc I have solved the problem with sorting the bam file.
