### ISSUE TITLE
errors running taxon_filter.py deplete_human

### ISSUE THREAD

**Issue by biocyberman** [broadinstitute/viral-ngs#575]
This is my script to call the python command

```
#!/usr/bin/env bash
BAM="$1"
bmtBAM=${BAM/.bam/_bmtagger.bam}
rmdubBAM=${BAM/.bam/_rmdup.bam}
blastBAM=${BAM/.bam/_blast.bam}
DATROOT="/data/resources/viralngs"
databases="$DATROOT/bmtagger/hg19  $DATROOT/bmtagger/GRCh37.68_ncRNA-GRCh37.68_transcripts-HS_rRNA_mitRNA $DATROOT/bmtagger/metagenomics_contaminants_v3"
blastdb="$DATROOT/blastdbs/metag_v3.ncRNA.mRNA.mitRNA.consensus"
taxon_filter.py deplete_human --bmtaggerDbs $databases \
                --blastDbs $blastdb --threads 12 --JVMmemory "10G" \
                --tmp_dir $PWD/tmp \
                --loglevel DEBUG \
                $BAM $bmtBAM $rmdubBAM $blastBAM >${BAM/.bam/.log}
```

And here is the error below. My current understand of the suite does not allow me to fix the error myself. So I need some help here:

```
./taxonfilter.sh IonXpress_002_trimmed_filtered.bam                                                                                                                                                                                           
2017-02-09 21:41:45,547 - cmd:182:main_argparse - INFO - software version: 1.13.4, python version: 2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:22:31) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
2017-02-09 21:41:45,548 - cmd:184:main_argparse - INFO - command: $HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/taxon_filter.py deplete_human JVMmemory=10G tmp_dir=$HOME/viralngs/tmp loglevel=DEBUG taxfiltBam=None bmtaggerBam=IonXpress_002_trimmed_filtered_bmtagger.bam rmdupBam=IonXpress_002_trimmed_filtered_rmdup.bam lastDb=None blastDbs=['/resources/viralngs/blastdbs/metag_v3.ncRNA.mRNA.mitRNA.consensus'] blastnBam=IonXpress_002_trimmed_filtered_blast.bam bmtaggerDbs=['/resources/viralngs/bmtagger/hg19', '/resources/viralngs/bmtagger/GRCh37.68_ncRNA-GRCh37.68_transcripts-HS_rRNA_mitRNA', '/resources/viralngs/bmtagger/metagenomics_contaminants_v3'] threads=12 revertBam=None inBam=IonXpress_002_trimmed_filtered.bam tmp_dirKeep=False
2017-02-09 21:41:45,550 - cmd:198:main_argparse - DEBUG - using tempDir: $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8
2017-02-09 21:41:47,264 - __init__:444:_attempt_install - DEBUG - Currently installed version of samtools: 1.3.1-5
2017-02-09 21:41:47,264 - samtools:52:execute - DEBUG - $HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/samtools view -H -o $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmp5bARnJ.txt IonXpress_002_trimmed_filtered.bam
2017-02-09 21:41:49,277 - __init__:444:_attempt_install - DEBUG - Currently installed version of bmtagger: 3.101-3
2017-02-09 21:41:50,950 - __init__:444:_attempt_install - DEBUG - Currently installed version of blast: 2.2.31-boost1.60_2
2017-02-09 21:41:53,078 - __init__:444:_attempt_install - DEBUG - Currently installed version of samtools: 1.3.1-5
2017-02-09 21:41:53,078 - samtools:52:execute - DEBUG - $HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/samtools bam2fq -1 $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmph8526u.1.fastq -2 $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmpGofTEQ.2.fastq IonXpress_002_trimmed_filtered.bam
[M::bam2fq_mainloop] processed 1188107 reads
2017-02-09 21:41:59,823 - taxon_filter:566:deplete_bmtagger_bam - DEBUG - $HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/bmtagger.sh -b /resources/viralngs/bmtagger/hg19.bitmask -C $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmpr3AE24.bmtagger.conf -x /resources/viralngs/bmtagger/hg19.srprism -T $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmp6dtPBo -q1 -1 $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmph8526u.1.fastq -2 $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmpGofTEQ.2.fastq -o $HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmphESbqw.txt
Traceback (most recent call last):
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/taxon_filter.py", line 1207, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/opt/viral-ngs-1.13.4/util/cmd.py", line 201, in main_argparse
    ret = args.func_main(args)
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/taxon_filter.py", line 126, in main_deplete_human
    JVMmemory=args.JVMmemory
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/taxon_filter.py", line 798, in multi_db_deplete_bam
    deplete_method(tmpBamIn, db, tmpBamOut, threads=threads, JVMmemory=JVMmemory)
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/taxon_filter.py", line 567, in deplete_bmtagger_bam
    util.misc.run_and_print(cmdline, check=True)
  File "$HOME/bin/opt/anaconda/envs/viral-ngs-env/opt/viral-ngs-1.13.4/util/misc.py", line 243, in run_and_print
    raise(e)

subprocess.CalledProcessError: Command '['$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/bmtagger.sh', '-b', '/resources/viralngs/bmtagger/hg19.bitmask', '-C', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmpr3AE24.bmtagger.conf', '-x', '/resources/viralngs/bmtagger/hg19.srprism', '-T', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmp6dtPBo', '-q1', '-1', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmph8526u.1.fastq', '-2', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmpGofTEQ.2.fastq', '-o', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-RbyvJ8/tmphESbqw.txt']' returned non-zero exit status 8subprocess.CalledProcessError: Command '['$HOME/bin/opt/anaconda/envs/viral-ngs-env/bin/bmtagger.sh', '-b', '/resources/viralngs/bmtagger/hg19.bitmask', '-C', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-axcrG1/tmpQOEQmf.bmtagger.conf', '-x', '/resources/viralngs/bmtagger/hg19.srprism', '-T', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-axcrG1/tmp3PeS6I', '-q1', '-1', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-axcrG1/tmp7r7avl.1.fastq', '-2', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-axcrG1/tmpE6FiU1.2.fastq', '-o', '$HOME/viralngs/tmp/tmp-taxon_filter-deplete_human-axcrG1/tmpiy_FiJ.txt']' returned non-zero exit status 8



```

**Comment by biocyberman** [comment]
Ok, my current tracing to the culprit: the call to samtools expects that my unaligned BAM file contain paired end reads, and discards all the singleton reads. I got nothing left after this step with iontorrent single end data.

**Comment by dpark01** [comment]
This depends on #238 -- actually this is probably the main step of the whole process where #238 is an issue. Sorry @biocyberman -- we've been a bit held up by paper deadlines and snow closures, but we are normally a bit more responsive and should be pinging back on these in the coming days.

**Comment by biocyberman** [comment]
@dpark01 I just need to get the dev/testing environment to work correctly and I can make pull request about these things. You know they are among the easiest things to hack :)

**Comment by dpark01** [comment]
Going to close this in favor of #238
